version: "3"
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-prometheus-datasource.yml:/etc/grafana/provisioning/datasources/prometheus-datasource.yml:ro
      - ./grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - /tmp/node-exporter-server-metrics-raw.json:/var/lib/grafana/dashboards/node-exporter-server-metrics-raw.json:ro
  node_exporter-v013:
    image: prom/node-exporter:v0.13.0
    ports:
      - "9101:9100"
  node_exporter-v016:
    image: prom/node-exporter:v0.16.0
    ports:
      - "9102:9100"
  node_exporter-master:
    image: prom/node-exporter:master
    ports:
      - "9103:9100"
